# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.default_email: '%env(MAILER_USER)%'
    pictures_directory: '%kernel.project_dir%/public/uploads/pictures'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Cocur\Slugify\Slugify: ~

    App\Service\FileManagerService:
        arguments:
            $targetDirectory: '%pictures_directory%'
    
    App\Twig\TwigVideoExtension:
        tags: ['twig.extension']
        arguments:
            $embedUrlTemplates: 
                youtu:  https://www.youtube.com/embed/%s?controls=2
                dai.ly: https://www.dailymotion.com/embed/video/%s
                daily:  https://www.dailymotion.com/embed/video/%s
                vimeo:  https://player.vimeo.com/video/%s
    
    App\Twig\TwigAvatarExtension:
        tags: ['twig.extension']
        arguments:
            $bgAllowedColors:
                - 012A4A%2Ffff
                - 013A63%2Ffff
                - 01497C%2Ffff
                - 2A6F97%2Ffff
                - 2C7DA0%2Ffff
                - 468FAF%2Ffff
                - 61A5C2%2Ffff
                - 89C2D9
                - A9D6E5
    
    App\Doctrine\Listener\PictureRemoveFileListener:
        tags:
            [
                {
                    name:   'doctrine.orm.entity_listener',
                    event:  postRemove,
                    entity: App\Entity\Picture
                }
            ]
    
